name: Build and deploy to GitHub pages for testing

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3.5.2
        with:
          persist-credentials: false
      - name: Install and Build ðŸ”§
        env:
          typesense_host: ${{ secrets.VITE_APP_TYPESENSE_HOST }}
          typesense_port: ${{ secrets.VITE_APP_TYPESENSE_PORT }}
          typesense_protocol: ${{ secrets.VITE_APP_TYPESENSE_PROTOCOL }}
          typesense_search_key: ${{ secrets.VITE_APP_TYPESENSE_SEARCH_KEY }}
          typesense_bischoff_index: ${{ secrets.VITE_APP_TYPESENSE_BISCHOFF_INDEX_NAME }}
          typesense_rumpf_index: ${{ secrets.VITE_APP_TYPESENSE_RUMPF_INDEX_NAME }}
          typesense_supplique_index: ${{ secrets.VITE_APP_TYPESENSE_SUPPLIQUE_INDEX_NAME }}
        run: | # Install npm packages and build the Storybook files
          npm install
          echo -e "VITE_APP_TYPESENSE_HOST=${typesense_host}\nVITE_APP_TYPESENSE_PORT=${typesense_port}\nVITE_APP_TYPESENSE_PROTOCOL=${typesense_protocol}\nVITE_APP_TYPESENSE_SEARCH_KEY=${typesense_search_key}\nVITE_APP_TYPESENSE_BISCHOFF_INDEX_NAME=${typesense_bischoff_index}\nVITE_APP_TYPESENSE_RUMPF_INDEX_NAME=${typesense_rumpf_index}\nVITE_APP_TYPESENSE_SUPPLIQUE_INDEX_NAME=${typesense_supplique_index}" >> .env

          echo "Using env:"
          cat .env
          npm run build-storybook
          touch ./storybook-static/.nojekyll
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: storybook-static # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
